version: '3'
services:
  ruby:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4567:4567
    volumes:
      - .:/myapp/
    depends_on:
      - redis
  redis:
    image: "redis"
    ports: 
      - 6379:6379
    